### ISSUE TITLE
Feedback on milestone #3

### ISSUE THREAD

**Issue by barryross** [captainspaceman/sl#2]
Thanks for the update on your final.  Nice to see you working on incorporating the mobile nav into here!  The site is coming together nicely!  Are you still planning on doing the modal with the single form in it, or thinking of just keeping the link to the Contact page?

**Comment by captainspaceman** [comment]
Thanks! Yeah it's a wild ride. I think that (for now) the link to the contact page is the way to go. I don't think I'll be able to elegantly get a modal working by Wednesday with all the mobile styling I want to get done.

**Comment by barryross** [comment]
I think that's a good call, and you can always work on adding on to it after your presentation

**Comment by captainspaceman** [comment]
...

**Comment by captainspaceman** [comment]
..
