### ISSUE TITLE
Feedback on final project

### ISSUE THREAD

**Issue by barryross** [captainspaceman/sl#3]
# FEWD Final Project

---

### Description

For the final project, you'll be designing and building a website of your choice. This project will test your knowledge of front-end web development and ask you to apply everything you've learned in this course. The result will be a website that you can add to your portfolio.  You could create: a portfolio website; a marketing website for a startup or business; or a prototype for a simple web-app. Work with your instructor and EIR's to create project goals that are realistic given the scope and timing of the class.

Student: Ryan Farrell

Project URL:  https://github.com/captainspaceman/sl

|                                          |                                |                        |                          |
| ---------------------------------------- | ------------------------------ | ---------------------- | ------------------------ |
| Technical Requirements                   | Does Not Meet Expectations (0) | Meets Expectations (1) | Exceeds Expectations (2) |
| Project Proposal / Wireframes turned in (milestone #1) |                                |                        | x                        |
| Draft of HTML/CSS turned in (milestone #2) |                                |                        | x                        |
| First draft of JS turned in week (milestone #3) |                                |                        | x                        |
| Updated rough draft of project week (milestone #4) |                                |                        | x                        |
| Final presentation (milestone #5)        |                                |                        | x                        |
| Use HTML5 structural elements (header, footer, nav, footer) |                                |                        | x                        |
| Demonstrate a correct use of classes and IDs |                                |                        | x                        |
| Use classes to identify a type of element and IDs for identifying a specific unique element on the page |                                |                        | x                        |
| Select the appropriate tags to markup content |                                |                        | x                        |
| Apply fonts, color and styles to elements and the page |                                |                        | x                        |
| Demonstrate use of floats (or inline-block) and the box model |                                |                        | x                        |
| Use JavaScript/jQuery to make pages interactive |                                |                        | x                        |
| TOTAL: 24/24                             |                                |                        |                          |

**Comment by barryross** [comment]
Ryan, great work on your final project!  

It's very cool to see you build on your design expertise with your newly acquired development skills.  I really appreciate seeing all of the work you put into the wireframes/mockups, planning etc and it is very cool that you revamped a site that you had initially designed!  

I'm very impressed by the attention to detail and consistency across your site. Fantastic job making it responsive as well!  

It has been a pleasure having you in class, and watching you embrace the challenge of new material, and grow as a front-end developer.  .Please feel free to keep in touch with regards to web/tech stuff, and I'll be in touch about music!

Great job! 💯

**Comment by captainspaceman** [comment]
Hey thanks, Barry! 

I am just now literally seeing this notification. You still at GA?
